### PR TITLE
WIP: First Draft for FindIt.png generation code

### PR DESCRIPTION
**Pull request by jon-kroko**
# TODO: Figures for 1st two chapters

### QuickTour figures

- [x] Blob.png (note: not renamed, even though it's now Bouncing Atoms)
- [x] BooleanHierarchyBrowser.png
- [ ] ~~Browser.png~~
- [x] ClassBrowser2.png
- [x] Doit.png
- [x] ExploreIt.png
- [x] FindIt.png
- [x] HelloWorld.png
- [x] InspectIt.png
- [x] Kernel-objects-boolean.png
- [x] MethodFinder-example1.png
- [x] OpenMenu.png
- [x] Predebugger.png
- [x] PreferenceBrowser.png
- [x] PrintIt.png
- [x] SqueakMap.png
- [x] String-Shout.png
- [x] StringTest-newMethodTemplate.png
- [x] TimeClasses.png
- [x] Tools.png
- [ ] ~~WorkspaceWithText.png (in MoreWorkspace.tex, but commented out...?)~~
- [ ] ~~annotatedDownload.graffle (not a squeak screenshot)~~
- [ ] ~~annotatedDownload.png (not a squeak screenshot)~~
- [x] cloverleafKey.png
- [x] colouredMouse.jpg
- [ ] ~~download.png (not a squeak screenshot)~~
- [ ] ~~killBlob.png (that type of morph is not up to date)~~
- [x] methodFinder-now.png
- [x] morphicHaloOnWorkspace.png
- [x] morphicRotate.png
- [x] saveAs.png
- [x] startup.png
- [x] testRunnerOnStringTest.png
- [x] testShoutConfirm.png
- [x] worldMenu.png
- [x] yellowButtonMenuOnWorkspace.png

### FirstApp figures

- [ ] ~~ANewRepository.png~~ (looks unused)
- [x] AcceptClassDef.png
- [x] AddCategory.png
- [x] BrowseRepository.png
- [x] Categorize.png
- [x] ClassTemplate.png
- [x] Debugger.png
- [x] DeclareInstanceVar.png
- [x] DragMethod.png
- [x] Error.png
- [ ] ~~FileIn.png~~
- [x] GameBoard.png
- [x] MonticelloBrowser.png
- [x] SBECell.png
- [x] SBECellInspector.png
- [x] SBECellResize.png
- [x] UnknownSelector.png

### CODE REVIEW

**Comment by tom95** [comment]
@jon-kroko @EatingBacon we now have a utility called `helper runModal: [] then: []` that you can use whenever you need to screenshot a modal dialog (that is every dialog that opens in Squeak when you have to confirm something like "Save before closing" when you try to close the image, or when you press Cmd+F in the browser and it displays the filterable list).

I included an example on how to use it for FindIt.png, in general you should put the code that opens the modal dialog in the first block (e.g. the shortcut that will trigger it) and anything you want to run after opening the dialog in the second block, e.g. repositioning the dialog, typing something into its search field...

**Comment by tom95** [comment]
Is the TODO list based on all the files from the folder? I believe some of them aren't actually used in the book. This expression should return all matches as well: `grep includegraphics *`

**Comment by tom95** [comment]
```
### MoreWorkspace.tex
- [ ] cloverleafKey
- [ ] WorkspaceWithText

### QuickTour.tex
- [ ] cloverleafKey
- [ ] annotatedDownload
- [ ] download
- [ ] startup
- [ ] worldMenu
- [ ] yellowButtonMenuOnWorkspace
- [ ] morphicHaloOnWorkspace
- [ ] colouredMouse
- [ ] morphicRotate
- [ ] PreferenceBrowser
- [ ] OpenMenu
- [ ] Blob
- [ ] saveAs
- [ ] Tools
- [ ] HelloWorld
- [ ] Doit
- [ ] PrintIt
- [ ] InspectIt
- [ ] SqueakMap
- [ ] ClassBrowser2
- [ ] Kernel
- [ ] FindIt
- [ ] TimeClasses
- [ ] FindIt
- [ ] TimeClasses
- [ ] methodFinder
- [ ] MethodFinder
- [ ] StringTest
- [ ] testShoutConfirm
- [ ] testRunnerOnStringTest
- [ ] Predebugger
- [ ] String

### FirstApp.tex
- [ ] GameBoard
- [ ] AddCategory
- [ ] ClassTemplate
- [ ] AcceptClassDef
- [ ] SBECell
- [ ] SBECellInspector
- [ ] SBECellResize
- [ ] UnknownSelector
- [ ] DeclareInstanceVar
- [ ] Categorize
- [ ] DragMethod
- [ ] Error
- [ ] Debugger
- [ ] FileIn
- [ ] MonticelloBrowser
- [ ] BrowseRepository
```

...didn't want to just overwrite it. This is the list I could gather from the .tex files directly. Maybe you could do a quick check if it seems to make sense and then copy it over if you like.

**Comment by EatingBacon** [comment]
@tom95 there are some figure references in the chapters. Do we just leave them referencing the old figures and focus on the actual displayed ones?
Or do we want the references figures to be new as well?

**Comment by tom95** [comment]
I didn't see any usages of BooleanHierarchyBrowser in the actual book, so I would say we can leave it out for now. Same for any other figure that's not actually used. Or did I misunderstand?

**Comment by codeZeilen** [comment]
Yes to what tom said. We only update figures that are actually used. No speculative work :)

**Comment by LinqLover** [comment]
Is ClassBrowser2.png still to do?

**Comment by LinqLover** [comment]
Regarding Tools.png:

> (shows an empty squeak image. wouldn't it make more sense to show some morph's halo in that part of the chapter?)

I just updated the screenshot, but the question about usefulness is remaining open.

**Comment by LinqLover** [comment]
Just updated the todo list. Is really each bold item assigned to a certain person? If you got stuck, please remove the tick or inform us!

Other open todos:
- Still some Processor errors in the extractor?
- Make travis green again
- Merging

**Comment by tom95** [comment]
Ah sorry, should have explained the list in detail. Strikethrough means unused, bold means problematic/has blocker and regular means untouched. At some point we started drafts for all items, which is why almost all items got to be bold.

**Comment by LinqLover** [comment]
So how do I know whether someone is working a certain item? @jon-kroko has compared the tick with a semaphore and I do not want to interrupt anyone :)

**Pull request merged**
