### PR TITLE
Codify figures (part 2) and improve generation framework

### PR DESCRIPTION
**Pull request by LinqLover**
See also the open questions in #21.

### CODE REVIEW

**Comment by LinqLover** [comment]
@codeZeilen Sorry to page you, is there any news about your review of these changes? Can I give you any assistance to finally get the new screenshots live? :-)

**Comment by codeZeilen** [comment]
Sorry for leaving this open for so long. You are absolutely right that we should wrap this up. I looked through everything and it looks really nice! Good to see most of the figures being up to date now :)

Some minor issues we might want to fix before merging:
 * Figure 1.9, 6.32 (And probably others) shows the "Temporary changeset for SBE recording" label in the world menu
 * Figure 6.17, 6.22, 6.24 could be somewhat smaller
 * (Figure 6.25 - 6.29 look very nice)
 * Figure 11.1 the drop shadow looks funny (no too important for merging this)
 * Figure 12.1 could be somewhat smaller

Do you want to fix these in this PR or would you prefer to open a second one after merging this one? I am fine with both ways :)

**Comment by LinqLover** [comment]
Thank's a lot for your feedback, @codeZeilen, I will apply your points as soon as possible in this PR.

What is about the open questions in https://github.com/codeZeilen/SqueakByExample-english/issues/21#issuecomment-549047036 (everything that does not have a checkmark)? Shall we leave all these figures as is? :-)

> Figure 11.1 the drop shadow looks funny (no too important for merging this)

This is because `#imageForm` does not support transparency at the moment. I will bring up this on squeak-dev.

**Comment by codeZeilen** [comment]
@LinqLover Thanks for working on this so soon! I would prefer merging this PR and than switching to a more fine-grained workflow. (Will make it easier to review changes quickly ;))

**Review by codeZeilen — APPROVED** [review]

**Comment by LinqLover** [comment]
@codeZeilen Alright, feel free to merge this at any time!

**Pull request merged**
